# Generated by Django 4.2.1 on 2023-05-26 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_pet'),
    ]

    operations = [
        migrations.CreateModel(
            name='animalSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=30)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.pet')),
            ],
        ),
    ]
